apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-default
  namespace: istio-system
spec:
  components:
    cni:
      enabled: true
      namespace: kube-system
    egressGateways:
    - enabled: true
      #k8s:
      #  replicaCount: 2
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
        env:
        - name: ISTIO_META_IDLE_TIMEOUT
          value: 30s
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443

        serviceAnnotations:
          service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
      name: istio-ingressgateway
  #hub: dockerhub.kb.cz/iao-sq013-pub/istio
  hub: docker.io/istio
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        zipkin:
          address: jaeger-collector-app.istio-system:9411
    enablePrometheusMerge: false
  profile: default
  tag: 1.17.2
  values:
    cni:
      excludeNamespaces:
      - istio-system
      - kube-system
#    gateways:
#      istio-ingressgateway:
#        autoscaleEnabled: false
    global:
      imagePullSecrets:
      - nexus3
      proxy:
        resources:
          limits:
            cpu: "0.7"
            memory: 400M
          requests:
            cpu: "0.1"
            memory: 40M
    pilot:
      autoscaleEnabled: false
      replicaCount: 2
      resources:
        requests:
          cpu: "0.7"
          memory: 750M
      traceSampling: 100
